export const SELECCIONAR_ESTADO = 'SELECCIONAR_ESTADO';
export const SELECCIONAR_MUNICIPIO = 'SELECCIONAR_MUNICIPIO';
export const SELECCIONAR_PROGRAMAS = 'SELECCIONAR_PROGRAMAS';
export const SELECCIONAR_IMPRESOS = 'SELECCIONAR_IMPRESOS';

